services:
  regional-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regional-manager
    ports:
      - "8100:8100"
      - "8101:8101"
    restart: unless-stopped